def reverse(lista): # ESTA FUNÇÃO DEFINE UMA NOVA LISTA COM OS ELEMENTOS EM ORDENAÇÃO INVERTIDA DA LISTA DE ENTRADA
  revList = []
  for i in range((len(lista))):
    revList.append(lista[(i + 1) * -1])
  return revList # RETURNA OUTRA LISTA, SEM MODIFICAR A LISTA DE ENTRADA

  # A COMPLEXIDADE NESTE CASO É O(n), POIS N É O TAMANHO DA LISTA DE ENTRADA, E EM TODOS OS CASOS O SOFTWARE DEVE EXECUTAR N VEZES O A INVERSÃO, BASEADO NO TAMANHO DA LISTA; PORTANTO O SOFTWARE SEMPRE VAI EXECUTAR N VEZES.
lista = [1, 2, 3, 4, 5, 6, 7]

exec = reverse(lista)

print(exec)

